"use client";

import { useState } from "react";
import toast from "react-hot-toast";
import { Check, Copy, Loader2, PenLine, Sparkles } from "lucide-react";
import { apiPost, errorMessage } from "@/lib/client";
import type { SnippetSuggestionResult } from "@/lib/types";

/** AI-generated title/meta rewrites for the project's CTR opportunities. */
export default function AiSnippets({ projectId }: { projectId: number }) {
  const [result, setResult] = useState<SnippetSuggestionResult | null>(null);
  const [running, setRunning] = useState(false);

  const run = async () => {
    setRunning(true);
    toast("Writing improved titles & meta descriptions…", { icon: "✍️" });
    try {
      const r = await apiPost<SnippetSuggestionResult>(`/api/projects/${projectId}/ai-snippets`);
      setResult(r);
      toast.success("Suggestions ready");
    } catch (error) {
      toast.error(errorMessage(error));
    } finally {
      setRunning(false);
    }
  };

  const copy = (text: string) => {
    void navigator.clipboard.writeText(text);
    toast.success("Copied");
  };

  return (
    <div className="rounded-2xl border border-border-base bg-bg-card p-5 shadow-card">
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <PenLine size={15} className="text-accent-blue" />
          <h3 className="text-sm font-bold text-text-primary">AI title &amp; meta rewrites</h3>
        </div>
        <button
          type="button"
          onClick={() => void run()}
          disabled={running}
          className="flex items-center gap-1.5 rounded-lg bg-gradient-to-r from-accent-blue to-violet-500 px-3 py-1.5 text-xs font-semibold text-white transition-opacity hover:opacity-90 disabled:opacity-50"
        >
          {running ? <Loader2 size={13} className="animate-spin" /> : <Sparkles size={13} />}
          {running ? "Writing…" : result ? "Regenerate" : "Suggest rewrites"}
        </button>
      </div>
      <p className="mt-0.5 text-xs text-text-secondary">
        Rewrites titles &amp; descriptions for queries that rank but under-perform on CTR.
      </p>

      {result ? (
        <div className="mt-4 space-y-3">
          {result.suggestions.map((s, i) => (
            <div key={i} className="rounded-xl border border-border-base bg-bg-secondary/40 p-3">
              <div className="flex flex-wrap items-center gap-2 text-xs">
                <span className="font-semibold text-text-primary">{s.keyword}</span>
                {s.position !== null ? (
                  <span className="text-text-muted">pos {s.position}</span>
                ) : null}
                <span className="text-accent-red">CTR {s.currentCtr}%</span>
                <span className="text-text-muted">→ exp {s.expectedCtr}%</span>
              </div>
              <div className="mt-2 space-y-1.5">
                <div className="flex items-start gap-2">
                  <span className="mt-0.5 w-12 shrink-0 text-[10px] font-semibold uppercase text-text-muted">
                    Title
                  </span>
                  <span className="flex-1 text-sm text-text-primary">{s.suggestedTitle}</span>
                  <button
                    type="button"
                    onClick={() => copy(s.suggestedTitle)}
                    className="text-text-muted transition-colors hover:text-text-primary"
                    aria-label="Copy title"
                  >
                    <Copy size={13} />
                  </button>
                </div>
                <div className="flex items-start gap-2">
                  <span className="mt-0.5 w-12 shrink-0 text-[10px] font-semibold uppercase text-text-muted">
                    Meta
                  </span>
                  <span className="flex-1 text-sm text-text-secondary">{s.suggestedMeta}</span>
                  <button
                    type="button"
                    onClick={() => copy(s.suggestedMeta)}
                    className="text-text-muted transition-colors hover:text-text-primary"
                    aria-label="Copy meta"
                  >
                    <Copy size={13} />
                  </button>
                </div>
              </div>
              {s.rationale ? (
                <p className="mt-2 flex items-center gap-1.5 text-xs text-accent-green">
                  <Check size={12} /> {s.rationale}
                </p>
              ) : null}
            </div>
          ))}
          <p className="text-center text-[11px] text-text-muted">
            Generated by {result.model}
          </p>
        </div>
      ) : null}
    </div>
  );
}
